= Release Process

This is document is targeted towards developers of this project. It describes how to perform a release, and how to publish the libraries to NPM.

== Publishing

These steps have only been tested on OSX. It will probably work on any 'nix variant. Windows 10 with developer 'nix shell is a distinct 'maybe'.

If you are cloning this project for your own devious purposes, see the **Using this project as a bootstrap** section, near the end.


=== Do once (AKA 'setup steps')

1) Create a github access token https://github.com/settings/tokens and save it in a file named `generate-changelog-token.local.txt`
1) Clean and build the project successfully

=== Do every release

**Only perform a release from Master branch**

===== Assumptions
1. You have no uncommitted code.
1. All changes intended for the release have already been merged to master.

===== Release Process
. Pull from origin/master
. Update your package version in package.json
. Verify the version number has been updated and that there are no other uncommitted changes.
. Run `./generate-changelog.sh patch`
.. This should only modify and `git add` the changelog file.
.. Execute the additional steps that are printed out to the console.
. Verify change log generated and that there are no uncommitted changes.
. Run NPM publish steps, below.

The following require your npm user account credentials. Adding a local `.npmrc` file with `username=foo` and `email=foo@example.com` can make this a bit nicer.

```shell
 # sign out of your normal account
> npm logout
 # Sign in to npm account
> npm login
> Username: ({`whoami`)
> Password:
> Email: (this IS public) (you@example.com)
> Logged in as `whoami` on https://registry.npmjs.org/.
> npm publish --access public
```
