import 'entityforge'

import './check/check.spec'
import './generate/data-gen.spec'
import './generate/boolean-gen.spec'
import './generate/enum-gen.spec'
import './generate/number-gen.spec'
import './generate/object-gen.spec'
import './generate/string-gen.spec'

import './forge/boolean-forge.spec'
import './forge/enum-forge.spec'
import './forge/number-forge.spec'
import './forge/string-forge.spec'
import './forge/object-forge.spec'
