import "./boolean-forge.spec"
import "./enum-forge.spec"
import "./number-forge.spec"
import "./object-forge.spec"
import "./string-forge.spec"
import "./reference-forge.spec"
import "./app-forge.spec"